add kr translate
r-lib/pkgdown pull request #1961
Opened 2021-12-09 13:08 UTC by mrchypark

https://github.com/r-lib/pkgdown/issues/1944

2021-12-09 13:41 UTC, hadley commented
Awesome, thanks! How was the experience of creating the translations? Were my instructions easy to follow?

And since I have no ability to review this, can you suggest any other Korean R users who would be able to take a look? If no, I'm sure I can recruit someone from twitter.

2021-12-09 13:43 UTC, mrchypark commented
@hadley Some work is confuse but your instructions are easy to follow.

I'll trying to ask any Korean R user to review this. And I'll let you know.

2021-12-12 19:37 UTC, mrchypark commented
@hadley maybe you recruit someone from twitter is better solution. I'm trying to recruit my chennal(twitter, facebook) in Korean, not yet.

2021-12-13 15:24 UTC, hadley commented
Will do, thanks!

2021-12-13 16:03 UTC, peremen requested changes

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "고문"
I would not say "고문" for those who advised my thesis in university...

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "(%s)에서 보기"
Why there are brackets surrounding %s?

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "소스코드 확인"
I would use "탐색" instead of "확인", if this is an action opening a source code repository. Also consider "소스 코드" instead of "소스코드".

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "변경사항"
Consider "변경 사항"

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "배포"
I would transliterate as "릴리스", but it is up to you.

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "세부사항"
Consider "세부 사항"

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "# %s 타입인 %s의 메소드"
"메소드" -> "메서드"

2021-12-13 16:03 UTC, peremen commented on po/R-kr.po
> +msgstr "예시코드"
Consider "예시 코드"

2021-12-13 16:08 UTC, mrchypark commented on po/R-kr.po
> +msgstr "고문"
Any suggestion?

2021-12-13 16:18 UTC, peremen commented on po/R-kr.po
> +"Language: kr\n"
Yes. Unfortunately I've seen too much of this mistake mixing up ko and kr.

2021-12-13 16:19 UTC, mrchypark commented on po/R-kr.po
> +"Language: kr\n"
https://www.fincher.org/Utilities/CountryLanguageList.shtml

I confuse your comment. Country code is ko and language code is kr.
Is that right?

2021-12-13 16:22 UTC, peremen commented on po/R-kr.po
> +"Language: kr\n"
No. language is ko, country is kr.

2021-12-13 16:24 UTC, mrchypark commented on po/R-kr.po
> +"Language: kr\n"
@peremen I fixed this. The first link I referenced was reversed. Thank you for letting me know.

2021-12-13 16:29 UTC, mrchypark commented on po/R-kr.po
> +msgstr "고문"
I thought the expression "지도 교수" for package making was odd.
Any other good expressions?

2021-12-13 16:36 UTC, mrchypark commented on po/R-kr.po
> +msgstr "소스코드 확인"
![image](https://user-images.githubusercontent.com/6179259/145851751-2a5634c7-fa70-4b92-9eab-16a4832d94b4.png)

2021-12-13 16:42 UTC, mrchypark commented on po/R-kr.po
> +msgstr "소스코드 확인"
`Browse source code` is hyper link to github repo. how about "소스코드 보기"?

2021-12-13 16:47 UTC, peremen commented on po/R-kr.po
> +msgstr "소스코드 확인"
Okay, that also sounds good.

2021-12-13 16:57 UTC, mrchypark commented on po/R-kr.po
> +msgstr "고문"
https://r-pkgs.org/description.html#author
https://www.loc.gov/marc/relators/relaterm.html

"지도 교수" looks like right choice.

2021-12-14 09:50 UTC, peremen reviewed
The R-ko.po file now looks okay. Could you also remove the changes in R-pkgdown.mo files of other languages? I think they are not supposed to be modified by this commit.

2021-12-14 10:03 UTC, mrchypark commented
@peremen Thank you for your support!

@hadley What should I do with the R-pkgdown.mo files?

2021-12-14 13:21 UTC, hadley commented
@mrchypark don't worry about them; I'll fix them up.

2021-12-14 13:22 UTC, mrchypark commented
@hadley good. Work is done. :)

2021-12-14 18:42 UTC, merged

2021-12-14 18:42 UTC, hadley commented
Thanks to both of you for contributing this!

2021-12-14 18:59 UTC, mrchypark commented
@hadley  he(@peremen) notice me to we use ko not kr.

2021-12-15 13:17 UTC, hadley commented
Oops, I'll fix.

2021-12-15 13:23 UTC, mrchypark commented
@hadley  Thank you for your kind work. :)