Adjust Rmd that use h1 as top-level headings
r-lib/pkgdown pull request #2006
Opened 2022-01-10 18:28 UTC by hadley

Fixes #2004. Closes #2005.

2022-01-11 09:43 UTC, maelle requested changes
The current version also includes the page title in the TOC. I am waiting for GitHub pages to prove my point when it updates https://maelle.github.io/blabla/articles/blip.html at last :sweat_smile:

2022-01-11 09:43 UTC, maelle commented on R/tweak-page.R
> +  # If top-level headings use h1, move eveything down one level
```suggestion
  # If top-level headings use h1, move everything down one level
```

2022-01-11 09:43 UTC, maelle commented on NEWS.md
> +* Vignettes/articles that use `<h1>` as top-level heading automatically have
I now wonder whether it's the right decision (here and for changelogs). The page title h1 should maybe not count in the hierarchy especially as it's styled differently anyway? In Google docs there's title, subtitle and then heading 1, heading 2 etc.

2022-01-11 09:43 UTC, maelle commented on R/tweak-page.R
> +    tweak_section_levels(html)
Actually the code should not move _everything_ down one level, only the non page-header header. 
When `tweak_section_levels()` is called for news it is only called on the content of NEWS.md i.e. without any page header.

2022-01-11 09:44 UTC, maelle commented
See https://github.com/r-lib/pkgdown/pull/2008/files via https://stackoverflow.com/a/38266762

2022-01-11 10:11 UTC, maelle commented
https://maelle.github.io/blabla/articles/blip.html is deployed at last and shows the page header is in the TOC.

2022-01-11 17:04 UTC, hadley commented
I think you're saying we shouldn't adjust the page header? I agree.

2022-01-11 17:34 UTC, merged

2022-01-11 19:43 UTC, mpadge commented
@hadley This PR only kinda works - the [first h1 ToC item on @maelle's vignette](https://maelle.github.io/blabla/articles/blop.html#one-cool-thing) does not list sub-(h2)-items, but instead unfolds the second h1 item. Plus it still fails for me locally, and only gives h2 items in the Toc. Likely causally related is that the `<aside>` element for the ToC is `h2`, so naturally ignores all `h1` items.

2022-01-12 02:50 UTC, hadley commented
@mpadge that looks like it was run prior to me final changes.

2022-01-12 05:58 UTC, maelle commented
I've updated the website and yes the first h1 in the TOC never unfolds https://maelle.github.io/blabla/articles/blop.html but I suspect it's because the section is too short. More of a bootstrap-toc/scrollspy thing @mpadge, I think. 

What was the local failure?

2022-01-12 09:49 UTC, mpadge commented
@maelle yeah, agreed, that's likely just a scrollspy thing, so no problem here. The local failure is likely caused by `nvim-r` which doesn't always play nicely with `withr::local_options()`. I can resolve it by using `build_site(new_process = TRUE)`. Thanks both!