Respect DESCRIPTION language.
r-lib/pkgdown pull request #2808
Opened 2024-11-06 13:23 UTC by jonthegeek

If the package authors have specified a Language in DESCRIPTION, default to that, rather than "en".

2024-11-06 13:26 UTC, llrs commented
Nice, note that some packages have several languages.

2024-11-06 13:27 UTC, jonthegeek commented
Good call. Will update to use the first one here. Can still be overridden in `_pkgdown.yml`

2024-11-06 14:00 UTC, jayhesselberth requested changes

2024-11-06 14:00 UTC, jayhesselberth commented on R/package.R
> +    return(pkg$meta$lang)
Can you please add a test for this?

2024-11-06 14:00 UTC, jayhesselberth commented on R/package.R
> +      return(regmatches(field, regexpr("[^,]+", field)))
Can you please add a test for this?

2024-11-06 14:52 UTC, jonthegeek commented on R/package.R
> +    return(pkg$meta$lang)
Added.

2024-11-06 14:52 UTC, jonthegeek commented on R/package.R
> +      return(regmatches(field, regexpr("[^,]+", field)))
Added.

2024-11-06 15:22 UTC, jayhesselberth approved these changes

2024-11-25 22:55 UTC, hadley approved these changes

2024-11-25 22:56 UTC, merged